services:
  drupal:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./modules:/var/www/html/sites/all/modules/custom
    depends_on:
      - database
  
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 